// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void Button_pressed(lv_event_t * e)
{
	// Your code here
	int perc = lv_bar_get_value(ui_Bar1);
	if(perc >= 100) lv_bar_set_value(ui_Bar1,0,LV_ANIM_OFF);
	_ui_bar_increment(ui_Bar1,5,LV_ANIM_OFF);
}
